version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: final
    container_name: prod-go-api-server
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    container_name: prod-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: production
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"